-- MySQL Script generated by MySQL Workbench
-- Wed 25 Feb 2026 11:42:30 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema refuge
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `refuge` ;

-- -----------------------------------------------------
-- Schema refuge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `refuge` DEFAULT CHARACTER SET utf8 ;
USE `refuge` ;

-- -----------------------------------------------------
-- Table `refuge`.`Espece`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Espece` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Espece` (
  `idEspece` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEspece`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Race`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Race` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Race` (
  `idRace` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NOT NULL,
  `Espece_idEspece` INT NOT NULL,
  PRIMARY KEY (`idRace`),
  INDEX `fk_Race_Espece_idx` (`Espece_idEspece` ASC) VISIBLE,
  CONSTRAINT `fk_Race_Espece`
    FOREIGN KEY (`Espece_idEspece`)
    REFERENCES `refuge`.`Espece` (`idEspece`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Animal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Animal` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Animal` (
  `idAnimal` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Age` SMALLINT UNSIGNED NULL,
  `HealthStatus` VARCHAR(45) NULL,
  `DateArrive` DATE NULL,
  `Race_idRace` INT NOT NULL,
  PRIMARY KEY (`idAnimal`),
  INDEX `fk_Animal_Race1_idx` (`Race_idRace` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_Race1`
    FOREIGN KEY (`Race_idRace`)
    REFERENCES `refuge`.`Race` (`idRace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Personne` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Prenom` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  `Adresse` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Veterinaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Veterinaire` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Veterinaire` (
  `idVeterinaire` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NULL,
  `Telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idVeterinaire`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`TypeSoin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`TypeSoin` ;

CREATE TABLE IF NOT EXISTS `refuge`.`TypeSoin` (
  `idTypeSoin` INT NOT NULL AUTO_INCREMENT,
  `Label` VARCHAR(45) NULL,
  PRIMARY KEY (`idTypeSoin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Soin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Soin` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Soin` (
  `idSoin` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `TypeSoin_idTypeSoin` INT NOT NULL,
  `Veterinaire_idVeterinaire` INT NOT NULL,
  `Animal_idAnimal` INT NOT NULL,
  PRIMARY KEY (`idSoin`),
  INDEX `fk_Soin_TypeSoin1_idx` (`TypeSoin_idTypeSoin` ASC) VISIBLE,
  INDEX `fk_Soin_Veterinaire1_idx` (`Veterinaire_idVeterinaire` ASC) VISIBLE,
  INDEX `fk_Soin_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Soin_TypeSoin1`
    FOREIGN KEY (`TypeSoin_idTypeSoin`)
    REFERENCES `refuge`.`TypeSoin` (`idTypeSoin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soin_Veterinaire1`
    FOREIGN KEY (`Veterinaire_idVeterinaire`)
    REFERENCES `refuge`.`Veterinaire` (`idVeterinaire`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Soin_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `refuge`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `refuge`.`Adoption`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `refuge`.`Adoption` ;

CREATE TABLE IF NOT EXISTS `refuge`.`Adoption` (
  `Animal_idAnimal` INT NOT NULL,
  `Personne_idPersonne` INT NOT NULL,
  `dateDepart` DATE NOT NULL,
  PRIMARY KEY (`Animal_idAnimal`, `Personne_idPersonne`),
  INDEX `fk_Animal_has_Personne_Personne1_idx` (`Personne_idPersonne` ASC) VISIBLE,
  INDEX `fk_Animal_has_Personne_Animal1_idx` (`Animal_idAnimal` ASC) VISIBLE,
  CONSTRAINT `fk_Animal_has_Personne_Animal1`
    FOREIGN KEY (`Animal_idAnimal`)
    REFERENCES `refuge`.`Animal` (`idAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Animal_has_Personne_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `refuge`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
