-- MySQL Script generated by MySQL Workbench
-- Wed 25 Feb 2026 03:12:21 PM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`TypeChambre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`TypeChambre` ;

CREATE TABLE IF NOT EXISTS `hotel`.`TypeChambre` (
  `idTypeChambre` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTypeChambre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Chambre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Chambre` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Chambre` (
  `numChambre` INT NOT NULL,
  `capacity` INT NULL,
  `TypeChambre_idTypeChambre` INT NOT NULL,
  PRIMARY KEY (`numChambre`),
  UNIQUE INDEX `numChambre_UNIQUE` (`numChambre` ASC) VISIBLE,
  INDEX `fk_Chambre_TypeChambre1_idx` (`TypeChambre_idTypeChambre` ASC) VISIBLE,
  CONSTRAINT `fk_Chambre_TypeChambre1`
    FOREIGN KEY (`TypeChambre_idTypeChambre`)
    REFERENCES `hotel`.`TypeChambre` (`idTypeChambre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Personne` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Personne` (
  `idPersonne` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(50) NOT NULL,
  `prenom` VARCHAR(50) NOT NULL,
  `dateNaissance` DATE NULL,
  `email` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Groupe` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Groupe` (
  `idGroupe` INT NOT NULL AUTO_INCREMENT,
  `Responsable_idPersonne` INT NOT NULL,
  PRIMARY KEY (`idGroupe`),
  INDEX `fk_Groupe_Personne1_idx` (`Responsable_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_Groupe_Personne1`
    FOREIGN KEY (`Responsable_idPersonne`)
    REFERENCES `hotel`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`TypePension`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`TypePension` ;

CREATE TABLE IF NOT EXISTS `hotel`.`TypePension` (
  `idTypePension` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTypePension`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Reservation` (
  `numReservation` VARCHAR(100) NOT NULL,
  `dateDebut` DATE NOT NULL,
  `dateFin` DATE NOT NULL,
  `coutTotal` DECIMAL NULL,
  `Chambre_numChambre` INT NOT NULL,
  `Groupe_idGroupe` INT NOT NULL,
  `TypePension_idTypePension` INT NOT NULL,
  PRIMARY KEY (`numReservation`),
  INDEX `fk_Reservation_Chambre_idx` (`Chambre_numChambre` ASC) VISIBLE,
  INDEX `fk_Reservation_Groupe1_idx` (`Groupe_idGroupe` ASC) VISIBLE,
  INDEX `fk_Reservation_TypePension1_idx` (`TypePension_idTypePension` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_Chambre`
    FOREIGN KEY (`Chambre_numChambre`)
    REFERENCES `hotel`.`Chambre` (`numChambre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Groupe1`
    FOREIGN KEY (`Groupe_idGroupe`)
    REFERENCES `hotel`.`Groupe` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_TypePension1`
    FOREIGN KEY (`TypePension_idTypePension`)
    REFERENCES `hotel`.`TypePension` (`idTypePension`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`TypePrestation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`TypePrestation` ;

CREATE TABLE IF NOT EXISTS `hotel`.`TypePrestation` (
  `idTypePrestation` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idTypePrestation`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Prestation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Prestation` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Prestation` (
  `idPrestation` INT NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NOT NULL,
  `costPerPersonne` DECIMAL NOT NULL,
  `TypePrestation_idTypePrestation` INT NOT NULL,
  PRIMARY KEY (`idPrestation`),
  INDEX `fk_Prestation_TypePrestation1_idx` (`TypePrestation_idTypePrestation` ASC) VISIBLE,
  CONSTRAINT `fk_Prestation_TypePrestation1`
    FOREIGN KEY (`TypePrestation_idTypePrestation`)
    REFERENCES `hotel`.`TypePrestation` (`idTypePrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Personne_has_Groupe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Personne_has_Groupe` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Personne_has_Groupe` (
  `Personne_idPersonne` INT NOT NULL,
  `Groupe_idGroupe` INT NOT NULL,
  PRIMARY KEY (`Personne_idPersonne`, `Groupe_idGroupe`),
  INDEX `fk_Personne_has_Groupe_Groupe1_idx` (`Groupe_idGroupe` ASC) VISIBLE,
  INDEX `fk_Personne_has_Groupe_Personne1_idx` (`Personne_idPersonne` ASC) VISIBLE,
  CONSTRAINT `fk_Personne_has_Groupe_Personne1`
    FOREIGN KEY (`Personne_idPersonne`)
    REFERENCES `hotel`.`Personne` (`idPersonne`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Personne_has_Groupe_Groupe1`
    FOREIGN KEY (`Groupe_idGroupe`)
    REFERENCES `hotel`.`Groupe` (`idGroupe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`Reservation_has_Prestation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`Reservation_has_Prestation` ;

CREATE TABLE IF NOT EXISTS `hotel`.`Reservation_has_Prestation` (
  `Reservation_numReservation` VARCHAR(100) NOT NULL,
  `Prestation_idPrestation` INT NOT NULL,
  `datePrestation` DATE NULL,
  `pourcentageReduction` DECIMAL NULL,
  PRIMARY KEY (`Reservation_numReservation`, `Prestation_idPrestation`),
  INDEX `fk_Reservation_has_Prestation_Prestation1_idx` (`Prestation_idPrestation` ASC) VISIBLE,
  INDEX `fk_Reservation_has_Prestation_Reservation1_idx` (`Reservation_numReservation` ASC) VISIBLE,
  CONSTRAINT `fk_Reservation_has_Prestation_Reservation1`
    FOREIGN KEY (`Reservation_numReservation`)
    REFERENCES `hotel`.`Reservation` (`numReservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_has_Prestation_Prestation1`
    FOREIGN KEY (`Prestation_idPrestation`)
    REFERENCES `hotel`.`Prestation` (`idPrestation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
